<?php
/**
 * GetCharactersCharacterIdWalletsTransactions200OkObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ESI
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.2.3.dev7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ESI;

/**
 * GetCharactersCharacterIdWalletsTransactions200OkObjectTest Class Doc Comment
 *
 * @category    Class */
// * @description wallet transaction
/**
 * @package     ESI
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdWalletsTransactions200OkObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetCharactersCharacterIdWalletsTransactions200OkObject"
     */
    public function testGetCharactersCharacterIdWalletsTransactions200OkObject()
    {

    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {

    }

    /**
     * Test attribute "clientType"
     */
    public function testPropertyClientType()
    {

    }

    /**
     * Test attribute "journalRefId"
     */
    public function testPropertyJournalRefId()
    {

    }

    /**
     * Test attribute "locationId"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "locationType"
     */
    public function testPropertyLocationType()
    {

    }

    /**
     * Test attribute "pricePerUnit"
     */
    public function testPropertyPricePerUnit()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "transactionDate"
     */
    public function testPropertyTransactionDate()
    {

    }

    /**
     * Test attribute "transactionFor"
     */
    public function testPropertyTransactionFor()
    {

    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {

    }

    /**
     * Test attribute "transactionType"
     */
    public function testPropertyTransactionType()
    {

    }

    /**
     * Test attribute "typeId"
     */
    public function testPropertyTypeId()
    {

    }

}
