<?php
/**
 * GetCharactersCharacterIdWalletsJournal200OkObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ESI
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.2.3.dev7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ESI;

/**
 * GetCharactersCharacterIdWalletsJournal200OkObjectTest Class Doc Comment
 *
 * @category    Class */
// * @description transaction
/**
 * @package     ESI
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdWalletsJournal200OkObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetCharactersCharacterIdWalletsJournal200OkObject"
     */
    public function testGetCharactersCharacterIdWalletsJournal200OkObject()
    {

    }

    /**
     * Test attribute "argumentName"
     */
    public function testPropertyArgumentName()
    {

    }

    /**
     * Test attribute "argumentValue"
     */
    public function testPropertyArgumentValue()
    {

    }

    /**
     * Test attribute "firstPartyId"
     */
    public function testPropertyFirstPartyId()
    {

    }

    /**
     * Test attribute "firstPartyType"
     */
    public function testPropertyFirstPartyType()
    {

    }

    /**
     * Test attribute "postTransactionBalance"
     */
    public function testPropertyPostTransactionBalance()
    {

    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {

    }

    /**
     * Test attribute "refId"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "refType"
     */
    public function testPropertyRefType()
    {

    }

    /**
     * Test attribute "secondPartyId"
     */
    public function testPropertySecondPartyId()
    {

    }

    /**
     * Test attribute "secondPartyType"
     */
    public function testPropertySecondPartyType()
    {

    }

    /**
     * Test attribute "taxAmount"
     */
    public function testPropertyTaxAmount()
    {

    }

    /**
     * Test attribute "taxRecieverId"
     */
    public function testPropertyTaxRecieverId()
    {

    }

    /**
     * Test attribute "transactionAmount"
     */
    public function testPropertyTransactionAmount()
    {

    }

    /**
     * Test attribute "transactionDate"
     */
    public function testPropertyTransactionDate()
    {

    }

}
